openapi: 3.0.0

info:
  version: 0.0.1
  title: MpShippingFeeCalculate Service
  description: The MpShippingFeeCalculate service

tags:
  - name: "MpShippingFeeCalculate"

paths:
  /shipping:
    get:
      summary: This is summary
      tags:
        - "MpShippingFeeCalculate"
      description: This is a description
      operationId: calculateShippingFee
      responses:
        "200":
          description: This means its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShippingFeeResponse'

components:
  schemas:
    ShippingFeeResponse:
      description: This is the ShippingFeeResponse model
      type: object
      properties:
        local:
          description: The name of book
          type: string
        zonal:
          description: The name of book
          type: string
        national:
          description: The name of book
          type: string